[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[env]
term = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"
option_as_alt = "Both"
blur = true
opacity = 0.9

[font]
normal.family = "FiraCode Nerd Font Propo"
size = 22

[general]
import = ["~/.config/alacritty/xcode.toml"]
