import = ["~/.config/alacritty/kanagawa.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 19
