[colors.primary]
foreground = "#dfdfe0"
background = "#292a30"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.selection]
text = "#dfdfe0"

[colors.normal]
black = "#414453"
red = "#ff8170"
green = "#78c2b3"
yellow = "#d9c97c"
blue = "#4eb0cc"
magenta = "#ff7ab2"
cyan = "#b281eb"
white = "#dfdfe0"

[colors.bright]
black = "#7f8c98"
red = "#ff8170"
green = "#acf2e4"
yellow = "#ffa14f"
blue = "#6bdfff"
magenta = "#ff7ab2"
cyan = "#dabaff"
white = "#dfdfe0"
