theme = "onedark"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
rulers = [80]


[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
    "diagnostics",
    "selections",
    "position",
    "file-encoding",
    "file-line-ending",
    "file-type",
]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
C-s = ":w"
H = ":buffer-previous"
L = ":buffer-next"
C-q = ":quit"
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
C = [
    "ensure_selections_forward",
    "extend_to_line_end",
    "delete_selection",
    "insert_mode",
]
C-j = "save_selection"
C-d = ["page_cursor_half_down", "align_view_center"]
C-u = ["page_cursor_half_up", "align_view_center"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"

[keys.normal."C-w"]
w = ":write-buffer-close"
